const SERVICE_DOMAIN = 'http://jspro-gateway-test.gcnao.cn'
const config = {
    SERVICE_API: {
        API: `${SERVICE_DOMAIN}/basedata-service`,
        QUESTION_API: `${SERVICE_DOMAIN}/question-service`,
        APP_SYSTEM_API: `${SERVICE_DOMAIN}/system-service`,
        INDEX_API: `${SERVICE_DOMAIN}/portal-service`,
        PORTAL_API: `${SERVICE_DOMAIN}/portal-service`,
        SYSTEM_API: `${SERVICE_DOMAIN}/system-service`,
        MODEL_API: `${SERVICE_DOMAIN}/model-service`,
        WBS_API: `${SERVICE_DOMAIN}/wbs-service`,
        ENTITYTYPE_API: `${SERVICE_DOMAIN}/entitytype-service`,
        RESOURCE_API: `${SERVICE_DOMAIN}/resource-service`,
        QUALITY_CHECK_API: `${SERVICE_DOMAIN}/qualitycheck-service`,
        VIDEO_API: `${SERVICE_DOMAIN}/jsbimpro-video-service`,
        VIDEO_JSPRO_API: `${SERVICE_DOMAIN}/jspro-video-service`,
        MIDDLEWARE_SERVICE: `${SERVICE_DOMAIN}/middleware-service`,
        DOC_VIEW_API: `${SERVICE_DOMAIN}/middleware-service`,
        STARTUP_API: `${SERVICE_DOMAIN}/startup-service`,
        CALQTY_API: `${SERVICE_DOMAIN}/calqty-service`,
        EXPERIMENT_API: `${SERVICE_DOMAIN}/experiment-service`,
        MONTHLY_REPORT_API:`${SERVICE_DOMAIN}/monthlyreport-service`,
        JSPRO_AGREEMENT_API:`${SERVICE_DOMAIN}/jspro-agreement-service`,
        MANPOWER_API:`${SERVICE_DOMAIN}/manpower-service`,
        FIELD_API:`${SERVICE_DOMAIN}/field-service`,
        DOCUMENT_API:`${SERVICE_DOMAIN}/document-service`,
        PAPER_API:`${SERVICE_DOMAIN}/paper-service`,
        ELEMENT_API:`${SERVICE_DOMAIN}/element-service`,
        REQUISITION_API:`${SERVICE_DOMAIN}/requisition-service`,
        CHANGE_API:`${SERVICE_DOMAIN}/change-service`,
        LEDGER_API:`${SERVICE_DOMAIN}/jspro-ledger-service`,
        QUALITYAPP_API:`${SERVICE_DOMAIN}/qualityapp-service-wxl`,
        MANAGETABLE_API:`${SERVICE_DOMAIN}/managetable-service`,
        SITECHECK_API:`${SERVICE_DOMAIN}/sitecheck-service`,
    },
}
export default config;